import {
  MESSAGES_TYPE,
  DIRECT_MESSAGE_TYPE,
  META_EVENT_LIFECYCLE,
  META_EVENT_HEARTBEAT,
  NOTICE_GROUP_UPLOAD_TYPE,
  NOTICE_OFFLINE_FILE_TYPE,
  NOTICE_GROUP_ADMIN_TYPE,
  NOTICE_NOTIFY_TYPE,
  NOTICE_FRIEND_ADD_TYPE
} from './types';

export type OneBotEventMap = {
  DIRECT_MESSAGE: DIRECT_MESSAGE_TYPE;
  MESSAGES: MESSAGES_TYPE;
  META: META_EVENT_LIFECYCLE | META_EVENT_HEARTBEAT;
  REQUEST_ADD_FRIEND: any;
  REQUEST_ADD_GROUP: any;
  NOTICE_GROUP_MEMBER_INCREASE: any;
  NOTICE_GROUP_MEMBER_REDUCE: any;
  NOTICE_GROUP_RECALL: any;
  NOTICE_FRIEND_RECALL: any;
  NOTICE_GROUP_BAN: any;
  NOTICE_GROUP_UPLOAD: NOTICE_GROUP_UPLOAD_TYPE;
  NOTICE_OFFLINE_FILE: NOTICE_OFFLINE_FILE_TYPE;
  NOTICE_GROUP_ADMIN: NOTICE_GROUP_ADMIN_TYPE;
  NOTICE_NOTIFY: NOTICE_NOTIFY_TYPE;
  NOTICE_FRIEND_ADD: NOTICE_FRIEND_ADD_TYPE;
};
