import { MESSAGES_TYPE, DIRECT_MESSAGE_TYPE, META_EVENT_LIFECYCLE, META_EVENT_HEARTBEAT } from './types';

export type OneBotEventMap = {
  DIRECT_MESSAGE: DIRECT_MESSAGE_TYPE;
  MESSAGES: MESSAGES_TYPE;
  META: META_EVENT_LIFECYCLE | META_EVENT_HEARTBEAT;
  REQUEST_ADD_FRIEND: any;
  REQUEST_ADD_GROUP: any;
  NOTICE_GROUP_MEMBER_INCREASE: any;
  NOTICE_GROUP_MEMBER_REDUCE: any;
};
