import { CHANNEL_TOPIC_UPDATE_TYPE } from './message/CHANNEL_TOPIC_UPDATE'
import { CHANNEL_UPDATE_TYPE } from './message/CHANNEL_UPDATE'
import { GUILD_MEMBER_ADD_TYPE } from './message/GUILD_MEMBER_ADD'
import { GUILD_MEMBER_REMOVE_TYPE } from './message/GUILD_MEMBER_REMOVE'
import { GUILD_MEMBER_UPDATE_TYPE } from './message/GUILD_MEMBER_UPDATE'
import { MESSAGE_CREATE_TYPE } from './message/MESSAGE_CREATE'
import { MESSAGE_DELETE_TYPE } from './message/MESSAGE_DELETE'
import { MESSAGE_REACTION_ADD_TYPE } from './message/MESSAGE_REACTION_ADD'
import { MESSAGE_UPDATE_TYPE } from './message/MESSAGE_UPDATE'
import { PRESENCE_UPDATE_TYPE } from './message/PRESENCE_UPDATE'
import { READY_TYPE } from './message/READY'
import { TYPING_START_TYPE } from './message/TYPING_START'
import { VOICE_CHANNEL_STATUS_UPDATE_TYPE } from './message/VOICE_CHANNEL_STATUS_UPDATE'
import { VOICE_STATE_UPDATE_TYPE } from './message/VOICE_STATE_UPDATE'

/**
 * discord事件map
 */
export type DCEventMap = {
  CHANNEL_TOPIC_UPDATE: CHANNEL_TOPIC_UPDATE_TYPE
  CHANNEL_UPDATE: CHANNEL_UPDATE_TYPE
  GUILD_MEMBER_ADD: GUILD_MEMBER_ADD_TYPE
  GUILD_MEMBER_REMOVE: GUILD_MEMBER_REMOVE_TYPE
  GUILD_MEMBER_UPDATE: GUILD_MEMBER_UPDATE_TYPE
  MESSAGE_CREATE: MESSAGE_CREATE_TYPE
  MESSAGE_DELETE: MESSAGE_DELETE_TYPE
  MESSAGE_REACTION_ADD: MESSAGE_REACTION_ADD_TYPE
  MESSAGE_UPDATE: MESSAGE_UPDATE_TYPE
  PRESENCE_UPDATE: PRESENCE_UPDATE_TYPE
  READY: READY_TYPE
  TYPING_START: TYPING_START_TYPE
  VOICE_CHANNEL_STATUS_UPDATE: VOICE_CHANNEL_STATUS_UPDATE_TYPE
  VOICE_STATE_UPDATE: VOICE_STATE_UPDATE_TYPE
  ERROR: any
}
