const AvailableIntentsEventsEnum = [
  'GUILDS',
  'MEMBERS',
  'GUILD_MODERATION',
  'GUILD_EMOJIS_AND_STICKERS',
  'GUILD_INTEGRATIONS',
  'GUILD_WEBHOOKS',
  'GUILD_INVITES',
  'GUILD_VOICE_STATES',
  'GUILD_PRESENCES',
  'GUILD_MESSAGES',
  'REACTIONS',
  'GUILD_MESSAGE_TYPING',
  'DIRECT_MESSAGES',
  'DIRECT_MESSAGE_REACTIONS',
  'DIRECT_MESSAGE_TYPING',
  'MESSAGE_CONTENT',
  'GUILD_SCHEDULED_EVENTS',
  'AUTO_MODERATION_CONFIGURATION',
  'AUTO_MODERATION_EXECUTION'
] as const

export type DCIntentsEnum = (typeof AvailableIntentsEventsEnum)[number]
