// 定义事件枚举
export enum ActionsEventEnum {
  MessageRecall = 'message.recall',
  MessageEdit = 'message.edit',
  MessageQuote = 'message.quote',
  MessageForward = 'message.forward',
  MessageTop = 'message.top',
  MessageUntop = 'message.untop',
  MessageLike = 'message.like',
  MessageUnlike = 'message.unlike',
  GuildCreate = 'guild.create',
  GuildDelete = 'guild.delete',
  GuildEdit = 'guild.edit',
  GuildQuit = 'guild.quit',
  GuildJoin = 'guild.join',
  MemberList = 'member.list',
  MemberAdd = 'member.add',
  MemberDelete = 'member.delete',
  MemberEdit = 'member.edit',
  RoleAdd = 'role.add',
  RoleDelete = 'role.delete',
  RoleEdit = 'role.edit',
  RoleList = 'role.list',
  ChannelCreate = 'channel.create',
  ChannelDelete = 'channel.delete',
  ChannelEdit = 'channel.edit',
  ChannelList = 'channel.list',
  CategoryCreate = 'category.create',
  CategoryDelete = 'category.delete',
  CategoryEdit = 'category.edit',
  CategoryList = 'category.list',
  MemberKickOut = 'member.kickOut',
  MemberBan = 'member.ban',
  MemberUnban = 'member.unban'
}
