import { C2C_MESSAGE_CREATE_TYPE } from './message/C2C_MESSAGE_CREATE'
import { GROUP_AT_MESSAGE_CREATE_TYPE } from './message/GROUP_AT_MESSAGE_CREATE'
import { READY_TYPE } from './message/READY'
export type QQBotGroupEventMap = {
  C2C_MESSAGE_CREATE: C2C_MESSAGE_CREATE_TYPE
  GROUP_AT_MESSAGE_CREATE: GROUP_AT_MESSAGE_CREATE_TYPE
  READY: READY_TYPE
  ERROR: any
}
