import { CHANNEL_TOPIC_UPDATE_TYPE } from './message/CHANNEL_TOPIC_UPDATE';
import { CHANNEL_UPDATE_TYPE } from './message/CHANNEL_UPDATE';
import { GUILD_MEMBER_ADD_TYPE } from './message/GUILD_MEMBER_ADD';
import { GUILD_MEMBER_REMOVE_TYPE } from './message/GUILD_MEMBER_REMOVE';
import { GUILD_MEMBER_UPDATE_TYPE } from './message/GUILD_MEMBER_UPDATE';
import { INTERACTION_CREATE_TYPE } from './message/INTERACTION_CREATE';
import { MESSAGE_CREATE_TYPE } from './message/MESSAGE_CREATE';
import { MESSAGE_DELETE_TYPE } from './message/MESSAGE_DELETE';
import { MESSAGE_REACTION_ADD_TYPE } from './message/MESSAGE_REACTION_ADD';
import { MESSAGE_UPDATE_TYPE } from './message/MESSAGE_UPDATE';
import { PRESENCE_UPDATE_TYPE } from './message/PRESENCE_UPDATE';
import { READY_TYPE } from './message/READY';
import { TYPING_START_TYPE } from './message/TYPING_START';
import { VOICE_CHANNEL_STATUS_UPDATE_TYPE } from './message/VOICE_CHANNEL_STATUS_UPDATE';
import { VOICE_STATE_UPDATE_TYPE } from './message/VOICE_STATE_UPDATE';

/**
 * Discord 事件映射表
 */
export type DCEventMap = {
  // GUILDS (1 << 0)
  GUILD_CREATE: any;
  GUILD_UPDATE: any;
  GUILD_DELETE: any;
  GUILD_ROLE_CREATE: any;
  GUILD_ROLE_UPDATE: any;
  GUILD_ROLE_DELETE: any;
  CHANNEL_CREATE: any;
  CHANNEL_UPDATE: CHANNEL_UPDATE_TYPE;
  CHANNEL_DELETE: any;
  CHANNEL_PINS_UPDATE: any;
  CHANNEL_TOPIC_UPDATE: CHANNEL_TOPIC_UPDATE_TYPE;
  THREAD_CREATE: any;
  THREAD_UPDATE: any;
  THREAD_DELETE: any;
  THREAD_LIST_SYNC: any;
  THREAD_MEMBER_UPDATE: any;
  THREAD_MEMBERS_UPDATE: any;
  STAGE_INSTANCE_CREATE: any;
  STAGE_INSTANCE_UPDATE: any;
  STAGE_INSTANCE_DELETE: any;

  // GUILD_MEMBERS (1 << 1)
  GUILD_MEMBER_ADD: GUILD_MEMBER_ADD_TYPE;
  GUILD_MEMBER_UPDATE: GUILD_MEMBER_UPDATE_TYPE;
  GUILD_MEMBER_REMOVE: GUILD_MEMBER_REMOVE_TYPE;

  // GUILD_MODERATION (1 << 2)
  GUILD_AUDIT_LOG_ENTRY_CREATE: any;
  GUILD_BAN_ADD: any;
  GUILD_BAN_REMOVE: any;

  // GUILD_EXPRESSIONS (1 << 3)
  GUILD_EMOJIS_UPDATE: any;
  GUILD_STICKERS_UPDATE: any;
  GUILD_SOUNDBOARD_SOUND_CREATE: any;
  GUILD_SOUNDBOARD_SOUND_UPDATE: any;
  GUILD_SOUNDBOARD_SOUND_DELETE: any;
  GUILD_SOUNDBOARD_SOUNDS_UPDATE: any;

  // GUILD_INTEGRATIONS (1 << 4)
  GUILD_INTEGRATIONS_UPDATE: any;
  INTEGRATION_CREATE: any;
  INTEGRATION_UPDATE: any;
  INTEGRATION_DELETE: any;

  // GUILD_WEBHOOKS (1 << 5)
  WEBHOOKS_UPDATE: any;

  // GUILD_INVITES (1 << 6)
  INVITE_CREATE: any;
  INVITE_DELETE: any;

  // GUILD_VOICE_STATES (1 << 7)
  VOICE_STATE_UPDATE: VOICE_STATE_UPDATE_TYPE;
  VOICE_CHANNEL_STATUS_UPDATE: VOICE_CHANNEL_STATUS_UPDATE_TYPE;
  VOICE_CHANNEL_EFFECT_SEND: any;

  // GUILD_PRESENCES (1 << 8)
  PRESENCE_UPDATE: PRESENCE_UPDATE_TYPE;

  // GUILD_MESSAGES (1 << 9)
  MESSAGE_CREATE: MESSAGE_CREATE_TYPE;
  MESSAGE_UPDATE: MESSAGE_UPDATE_TYPE;
  MESSAGE_DELETE: MESSAGE_DELETE_TYPE;
  MESSAGE_DELETE_BULK: any;

  // GUILD_MESSAGE_REACTIONS (1 << 10)
  MESSAGE_REACTION_ADD: MESSAGE_REACTION_ADD_TYPE;
  MESSAGE_REACTION_REMOVE: any;
  MESSAGE_REACTION_REMOVE_ALL: any;
  MESSAGE_REACTION_REMOVE_EMOJI: any;

  // GUILD_MESSAGE_TYPING (1 << 11)
  TYPING_START: TYPING_START_TYPE;

  // DIRECT_MESSAGES (1 << 12)
  // (与 GUILD_MESSAGES 类似，但发生在私信频道)
  DIRECT_MESSAGE_CREATE: any;
  DIRECT_MESSAGE_UPDATE: any;
  DIRECT_MESSAGE_DELETE: any;
  DIRECT_MESSAGE_PINS_UPDATE: any;

  // DIRECT_MESSAGE_REACTIONS (1 << 13)
  DIRECT_MESSAGE_REACTION_ADD: any;
  DIRECT_MESSAGE_REACTION_REMOVE: any;
  DIRECT_MESSAGE_REACTION_REMOVE_ALL: any;
  DIRECT_MESSAGE_REACTION_REMOVE_EMOJI: any;

  // DIRECT_MESSAGE_TYPING (1 << 14)
  DIRECT_MESSAGE_TYPING_START: any;

  // MESSAGE_CONTENT (1 << 15)
  // (无独立事件，但影响 MESSAGE_CREATE 等事件的内容权限)

  // GUILD_SCHEDULED_EVENTS (1 << 16)
  GUILD_SCHEDULED_EVENT_CREATE: any;
  GUILD_SCHEDULED_EVENT_UPDATE: any;
  GUILD_SCHEDULED_EVENT_DELETE: any;
  GUILD_SCHEDULED_EVENT_USER_ADD: any;
  GUILD_SCHEDULED_EVENT_USER_REMOVE: any;

  // AUTO_MODERATION_CONFIGURATION (1 << 20)
  AUTO_MODERATION_RULE_CREATE: any;
  AUTO_MODERATION_RULE_UPDATE: any;
  AUTO_MODERATION_RULE_DELETE: any;

  // AUTO_MODERATION_EXECUTION (1 << 21)
  AUTO_MODERATION_ACTION_EXECUTION: any;

  // GUILD_MESSAGE_POLLS (1 << 24)
  MESSAGE_POLL_VOTE_ADD: any;
  MESSAGE_POLL_VOTE_REMOVE: any;

  // DIRECT_MESSAGE_POLLS (1 << 25)
  DIRECT_MESSAGE_POLL_VOTE_ADD: any;
  DIRECT_MESSAGE_POLL_VOTE_REMOVE: any;

  // 其他通用事件
  READY: READY_TYPE;
  INTERACTION_CREATE: INTERACTION_CREATE_TYPE;
};
