export const AvailableIntentsEventsEnum = [
  'GUILDS',
  'GUILD_MEMBERS',
  'GUILD_MODERATION',
  'GUILD_EXPRESSIONS',
  'GUILD_INTEGRATIONS',
  'GUILD_WEBHOOKS',
  'GUILD_INVITES',
  'GUILD_VOICE_STATES',
  'GUILD_PRESENCES',
  'GUILD_MESSAGES',
  'GUILD_MESSAGE_REACTIONS',
  'GUILD_MESSAGE_TYPING',
  'DIRECT_MESSAGES',
  'DIRECT_MESSAGE_REACTIONS',
  'DIRECT_MESSAGE_TYPING',
  'MESSAGE_CONTENT',
  'GUILD_SCHEDULED_EVENTS',
  'AUTO_MODERATION_CONFIGURATION',
  'AUTO_MODERATION_EXECUTION',
  'GUILD_MESSAGE_POLLS',
  'DIRECT_MESSAGE_POLLS'
]

export type DCIntentsEnum = (typeof AvailableIntentsEventsEnum)[number]
