# 具体见 pm2.config.cjs
pm2:
  apps:
    - name: 'gui'
      script: 'node index.js --login gui'
      env:
        NODE_ENV: 'production'

# websocket 服务器配置,可用于本地调试和插件开发
cbp:
  enable: false
  port: 17117
  plugins:
    '@alemonjs/testone':
      # 是否开启
      enable: false

# 一般功能模块，本地开发可通过 start('./xxx') 来开启指定
modules:
  'alemonjs-game':
    enable: false

# 应用插件，该插件会植入到应用进程中
plugins:
  '@alemonjs/web':
    port: 17118
    enable: false
